#!/usr/bin/env python
"""This script is to prepare the input data file used in program Cafe for 
gene family analysis. For example, python ../../../Scripts/prepare_cafe.py 
-i mclOutput2 -o mytest -s thaliatha axillaris inflata attenuata annuum 
sinuosa lycopersicum tuberosum"""

import argparse


def prepare_cafe(infile, outfile, species):
	""" prepare the input data file used in program Cafe for gene family analysis"""
	count = 1
	subtitle='\t'.join(species)
	outfile.write("Description\tID\t"+subtitle+'\n')
	
	for line in infile:
		gene_num = [ 0 for x in xrange(len(species))]		
		s = line.rstrip()
		orths = list(s.split('\t'))

		for x in xrange(len(orths)):
			lineage = orths[x].split('|')[0]

			for y in xrange(len(species)):
				if lineage == species[y]:
					gene_num[y] += 1
		
		if sum(gene_num) == 0: continue	
		gene_num = [str(x) for x in gene_num]
		print s
		
		outfile.write('NA'+'\tcluster_'+str(count)+'\t'+'\t'.join(gene_num)+'\n')
		count += 1
	
	
def main():
	parser = argparse.ArgumentParser(prog="cafe_input.py", description=__doc__,
	formatter_class=argparse.ArgumentDefaultsHelpFormatter)
	parser.add_argument('-i', '--infile', \
	help=("the output generated by orthoMCL"), required=True)
	parser.add_argument('-o', '--output', \
	help=("the output file"), required=True)
	parser.add_argument('-s', '--species', \
	help=("species names"), nargs='*',required=True)
	args = parser.parse_args()
	
	infile = open(args.infile, "r")
	outfile = open(args.output, "w")
	species = list(args.species)

	#print species
	prepare_cafe(infile, outfile, species)
		
	infile.close()
	outfile.close()
	
	
	
if __name__ == "__main__":
	main()
