#!/usr/bin/env python
"""This script is to  parse the output from orthoMCL program, in order to 
extract lineage-specific genes from a particular species.
"""

import argparse, itertools


def uniq_family(infile, species):
	for line in infile:
		s = line.rstrip()
		orths = list(s.split('\t'))
		ids = []
		for x in xrange(len(orths)):
			item = orths[x].split('|')[0] 
			ids.append(item)
		target = list(set(ids))
		if len(target) == 1 and target[0] == species:
			for key in orths:
				print key.split('|')[1] 
		


def main():
	parser = argparse.ArgumentParser(prog="ineage_specific_genes.py", description=__doc__,
	formatter_class=argparse.ArgumentDefaultsHelpFormatter)
	parser.add_argument('-i', '--infile', \
	help=("the output generated by orthoMCL"), required=True)
	parser.add_argument('-s', '--species', \
	help=("the particular species"), required=True)
	args = parser.parse_args()
	
	infile = open(args.infile, "r")
	species = args.species
	
	mydata = uniq_family(infile, species)
	infile.close()



if __name__ == "__main__":
	main()